// Generated by gencpp from file darknet_ros_msgs/img.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_IMG_H
#define DARKNET_ROS_MSGS_MESSAGE_IMG_H

#include <ros/service_traits.h>


#include <darknet_ros_msgs/imgRequest.h>
#include <darknet_ros_msgs/imgResponse.h>


namespace darknet_ros_msgs
{

struct img
{

typedef imgRequest Request;
typedef imgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct img
} // namespace darknet_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::darknet_ros_msgs::img > {
  static const char* value()
  {
    return "359be61846392affdfa43a82630b4f76";
  }

  static const char* value(const ::darknet_ros_msgs::img&) { return value(); }
};

template<>
struct DataType< ::darknet_ros_msgs::img > {
  static const char* value()
  {
    return "darknet_ros_msgs/img";
  }

  static const char* value(const ::darknet_ros_msgs::img&) { return value(); }
};


// service_traits::MD5Sum< ::darknet_ros_msgs::imgRequest> should match 
// service_traits::MD5Sum< ::darknet_ros_msgs::img > 
template<>
struct MD5Sum< ::darknet_ros_msgs::imgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::darknet_ros_msgs::img >::value();
  }
  static const char* value(const ::darknet_ros_msgs::imgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::darknet_ros_msgs::imgRequest> should match 
// service_traits::DataType< ::darknet_ros_msgs::img > 
template<>
struct DataType< ::darknet_ros_msgs::imgRequest>
{
  static const char* value()
  {
    return DataType< ::darknet_ros_msgs::img >::value();
  }
  static const char* value(const ::darknet_ros_msgs::imgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::darknet_ros_msgs::imgResponse> should match 
// service_traits::MD5Sum< ::darknet_ros_msgs::img > 
template<>
struct MD5Sum< ::darknet_ros_msgs::imgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::darknet_ros_msgs::img >::value();
  }
  static const char* value(const ::darknet_ros_msgs::imgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::darknet_ros_msgs::imgResponse> should match 
// service_traits::DataType< ::darknet_ros_msgs::img > 
template<>
struct DataType< ::darknet_ros_msgs::imgResponse>
{
  static const char* value()
  {
    return DataType< ::darknet_ros_msgs::img >::value();
  }
  static const char* value(const ::darknet_ros_msgs::imgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_IMG_H
