local_costmap:
  # global_frame: odom
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.5

  update_frequency: 15.0  #25
  publish_frequency: 15.0  #20 

  rolling_window: True
  width: 1.5
  height: 1.5
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    
